# Generated by Django 4.0.2 on 2022-02-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Stamp',
        ),
    ]
