# Generated by Django 4.0.2 on 2022-02-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stamp',
            old_name='age',
            new_name='release_year',
        ),
        migrations.RenameField(
            model_name='stamp',
            old_name='breed',
            new_name='style',
        ),
    ]
