# Generated by Django 4.0.2 on 2022-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_age_stamp_release_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='release_year',
        ),
        migrations.AddField(
            model_name='stamp',
            name='country',
            field=models.CharField(default='China', max_length=100),
        ),
    ]
