# Generated by Django 4.0.2 on 2022-02-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='stamp',
            name='owners',
            field=models.ManyToManyField(to='main_app.Owner'),
        ),
    ]
